routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/home', function () { return redirect()->route('home'); })->name("main");
Route::get('/loader', function () { return view('management.dashboard.loader'); })->name("loader");

Auth::routes();
Route::group(['middleware' => ['auth','parking_stop_if_blocked']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/card', 'UserController@card')->name('card');
    Route::get('/plate-sticker', 'UserController@plateSticker')->name('plateSticker');

});

Route::group(['prefix' =>'admin','namespace'=>'Admin'], function () {
    // Admin Login Routes
    Route::get('/login','Auth\LoginController@showLoginForm')->name('admin.login');
    Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('/register','Auth\RegisterController@register');
    Route::post('/login','Auth\LoginController@login');
    Route::post('/logout','Auth\LoginController@logout')->name('admin.logout');
    //Forgot Password Routes
    Route::get('/password/reset','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    //Reset Password Routes
    Route::get('/password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/password/reset','Auth\ResetPasswordController@reset')->name('password.update');
});

Route::group(['prefix' =>'admin','namespace'=>'Admin','as' => 'admin.','middleware' => ['auth:admin']], function () {
    Route::get('/',function(){ return redirect()->route('admin.dashboard'); })->name('home');
    Route::get('/dashboard','HomeController@index')->name('dashboard');
    Route::get('/managements','ManagementController@managements')->name('managements');
    Route::get('/management/add','ManagementController@addManagement')->name('addManagement');
    Route::post('/add-management','ManagementController@addManagementPost')->name('addManagementPost');
    Route::get('/ajax-managements','ManagementController@ajaxManagements')->name('ajaxManagements');
    Route::get('/management/edit/{id}','ManagementController@editManagement')->name('editManagement');
    Route::post('/edit-management','ManagementController@editManagementPost')->name('editManagementPost');
    Route::get('/management/block/{id}','ManagementController@blockManagement')->name('blockManagement');

    Route::get('/vehicle/types','ManagementController@vehicleTypes')->name('vehicleTypes');
    Route::get('/vehicle/types/edit/{id}','ManagementController@editVehicleType')->name('editVehicleType');
    Route::post('/vehicle/types/edit/{id}/post','ManagementController@editVehicleTypePost')->name('editVehicleTypePost');

    Route::get('/vehicle/types/add','ManagementController@addVehicleType')->name('addVehicleType');
    Route::post('/vehicle/types/add','ManagementController@addVehicleTypePost')->name('addVehicleTypePost');
    Route::get('/ajax-vehicle/types/','ManagementController@ajaxVehicleType')->name('ajaxVehicleType');

    Route::get('/location','LocationController@location')->name('location');
    Route::get('/location/add','LocationController@addLocations')->name('addLocations');
    Route::post('/add-locations','LocationController@addLocationPost')->name('addLocationPost');
    Route::get('/ajax-locations','LocationController@ajaxLocation')->name('ajaxLocation');
    Route::get('/location/edit/{id}','LocationController@editLocation')->name('editLocation');
    Route::post('/edit-location/post','LocationController@editLocationPost')->name('editLocationPost');
    Route::get('/location/block/{id}','LocationController@blockLocation')->name('blockLocation');
    Route::get('/location/map/{id}','LocationController@map')->name('map');
    Route::post('/location/map/{id}/post','LocationController@mapPost')->name('mapPost');

    Route::get('/location/{id}','LocationController@viewLocation')->name('viewLocation');

    Route::get('/slots/{id}','LocationController@addSlots')->name('addSlots');
    Route::post('/location/add/post','LocationController@addSlotPost')->name('addSlotPost');
    Route::get('/ajax-slots','LocationController@ajaxSlots')->name('ajaxSlots');
    Route::get('/slots/block/{id}','LocationController@blockSlot')->name('blockSlot');

    Route::get('/user-type','ManagementController@usersTypes')->name('usersTypes');
    Route::get('/user-type/add','ManagementController@addUserType')->name('addUserType');
    Route::post('/user-type/add/post','ManagementController@addUserTypePost')->name('addUserTypePost');
    Route::get('/ajax/users/','ManagementController@ajaxUserType')->name('ajaxUserType');

    Route::get('/users','ManagementController@users')->name('users');
    Route::get('/users/add','ManagementController@addUsers')->name('addUsers');
    Route::post('/users/add/post','ManagementController@addUserPost')->name('addUserPost');
    Route::post('/ajax-check-user-type','ManagementController@ajaxCheckUserType')->name('ajaxCheckUserType');
    Route::get('/ajax-users','ManagementController@ajaxUsers')->name('ajaxUsers');
    Route::post('/users-vehicles','ManagementController@usersVehicles')->name('usersVehicles');
    Route::get('/recharge/{id}','ManagementController@recharge')->name('recharge');
    Route::post('/recharge/{id}/post','ManagementController@rechargePost')->name('rechargePost');
    Route::get('/user/block/{id}','ManagementController@blockUser')->name('blockUser');


    Route::get('/parking-detail','ParkingController@parkingDetail')->name('parkingDetail');
    Route::get('/ajax-parking-detail','ParkingController@ajaxParkingDetail')->name('ajaxParkingDetail');







  });

  Route::group(['prefix' =>'management','namespace'=>'Management'], function () {
    // Admin Login Routes
    Route::get('/login','Auth\LoginController@showLoginForm')->name('management.login');
    Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('management.register');
    Route::post('/register','Auth\RegisterController@register');
    Route::post('/login','Auth\LoginController@login');
    Route::post('/logout','Auth\LoginController@logout')->name('management.logout');
    //Forgot Password Routes
});

Route::group(['prefix' =>'management','namespace'=>'Management','middleware' => ['auth:management','stop_if_blocked']], function () {
    Route::get('/',function(){ return redirect()->route('management.dashboard'); })->name('management.home');
    //Route::get('/dashboard','HomeController@index')->name('management.dashboard');
    Route::get('/dashboard',function(){ return redirect()->route('management.checkPoint'); })->name('management.dashboard');
    Route::get('/check-point/in','ManagementController@checkPoint')->name('management.checkPoint');
    Route::post('/ajax-check-user','ManagementController@ajaxVerifyUser')->name('management.ajaxVerifyUser');
    Route::get('/check-point/out','ManagementController@checkPointOut')->name('management.checkPointOut');
    Route::post('/ajax-check-point/out','ManagementController@ajaxVerifyUserOut')->name('management.ajaxVerifyUserOut');


  });

app/Http/Controllers/Admin/LocationController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use Auth;
use DataTables;
use Illuminate\Support\Facades\Validator;
use App\Model\Management;
use Illuminate\Support\Facades\Hash;
use Redirect;
use App\Model\Location;
use App\Model\VehicleType;
use App\Model\Slot;
use App\Model\UserType;

class LocationController extends Controller
{

    public function location()
    {

        return view('admin.locations.locations');
    }

    public function addLocations()
    {
        $vehicle_types = VehicleType::where('institute_id',Auth::guard('admin')->user()->institute_id)->get();
        $user_types = UserType::where('institute_id',Auth::guard('admin')->user()->institute_id)->get();
        return view('admin.locations.add-locations',compact('vehicle_types','user_types'));
    }
    public function addLocationPost(Request $request)
    {

        $validator =  Validator::make($request->all(),[
            'name' => 'required|min:3',
            'vehicle_type_id' => 'required',

        ]);

        if($request->input('is_paid')==1){
            $validator =  Validator::make($request->all(),[
                'price' => 'required',
            ]);
        }
        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        }

        Location::create([
            'name' => $request->input('name'),
            'institute_id' => Auth::guard('admin')->user()->institute_id,
            'admin_id' => Auth::guard('admin')->user()->id,
            'is_paid' => $request->input('is_paid'),
            'price' => $request->input('price'),
            'vehicle_type_id' => $request->input('vehicle_type_id'),
            'user_type_id'=>$request->input('user_type_id')

        ]);
        $request->session()->flash('message', 'Location created successfully!');
        return Redirect::back();
    }
    public function ajaxLocation(Request $request)
    {
        $location=Location::select('locations.*','vehicle_type.name as vehicle_type_name','user_type.name as user_type_name')
            ->where('locations.institute_id',Auth::guard('admin')->user()->institute_id)
            ->join("vehicle_type","vehicle_type.id","locations.vehicle_type_id")
            ->join("user_type","user_type.id","locations.user_type_id");

        return DataTables::of($location)->make(true);
    }
    public function editLocation($id)
    {
        $location = Location::find($id);
        $vehicle_types = VehicleType::where('institute_id',Auth::guard('admin')->user()->institute_id)->get();

        return view('admin.locations.edit-locations',compact('location','vehicle_types'));
    }
    public function editLocationPost(Request $request){

        $validator =  Validator::make($request->all(),[
            'name' => 'required|min:3',
            'vehicle_type_id' => 'required',

        ]);

        if($request->input('is_paid')==1){
            $validator =  Validator::make($request->all(),[
                'price' => 'required',
            ]);
        }
        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        }

        $location = Location::find( $request->input('id'));
        $location->name = $request->input('name');
        $location->is_paid = $request->input('is_paid');
        $location->price = $request->input('price');
        $location->vehicle_type_id = $request->input('vehicle_type_id');
        $location->save();
        $request->session()->flash('message', 'Location updated successfully!');
        return Redirect::back();
    }
    public function blockLocation($id,Request $request){
        $location = Location::where('id',$id)->first();
        if($location->is_active==1){
            $location->is_active=0;
            $request->session()->flash('error', 'User : '.$location->name.' blocked!');

        }else if($location->is_active==0){
            $location->is_active=1;
            $request->session()->flash('message', 'User : '.$location->name.' unblocked!');

        }
        $location->save();

        return Redirect::back();

    }
    public function viewLocation($id)
    {
        $location = Location::find($id);
        return view('admin.locations.slots',compact('location'));
    }
    public function addSlots($id){
        $location = Location::find($id);
        return view('admin.locations.add-slots',compact('location'));
    }
    public function addSlotPost(Request $request){

        $validator =  Validator::make($request->all(),[
            'location_id' => 'required',
            'number_of_slots' => 'required',
            'starting_slots' => 'required',
            //'ending_slots' => 'required',
        ]);


        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        }
        $starting_slots = $request->input('starting_slots');
        $location_id = $request->input('location_id');
        $number_of_slots = $request->input('number_of_slots');
        for($i= $starting_slots; $i<=(($starting_slots+$number_of_slots)-1); $i++){
            $slot_id=$i;
            $slot = Slot::where('slot_id',$slot_id)
            ->where('location_id',$location_id)
            ->where('institute_id',Auth::guard('admin')->user()->institute_id)
            ->first();
            if($slot){
                $request->session()->flash('error', 'Slot ID : '.$slot->slot_id.' already exist!');
                return Redirect::back();

            }
        }
        for($i= $starting_slots; $i<=(($starting_slots+$number_of_slots)-1); $i++){
            $slot_id=$i;
            $slot = Slot::create([
                'slot_id'=> $slot_id,
                'location_id'=> $location_id,
                'admin_id'=>Auth::guard('admin')->user()->id,
                'institute_id'=>Auth::guard('admin')->user()->institute_id
            ]);
        }
        $total_locations = Slot::where('location_id',$location_id)
            ->where('institute_id',Auth::guard('admin')->user()->institute_id)
            ->count();
        $loc = Location::find($location_id);
        $loc->number_of_slots = $total_locations;
        $loc->save();
        $request->session()->flash('message', 'Slots created successfully!');
        return redirect()->route('admin.viewLocation',$location_id);
    }
    public function ajaxSlots(Request $request){
       $location_id =  $request->input('location_id');
       $locations = Slot::select("slots.*","vehicles.vehicle_number as number_plate")
       ->where('location_id',$location_id)
            ->where('slots.institute_id',Auth::guard('admin')->user()->institute_id)
            ->leftJoin('user_slots', function ($join) {
                $join->on('user_slots.slot_id','=','slots.id');
                $join->where('user_slots.status','=',1);
                //$join->where('slot_vehicle.status','=',1);
                //$join->where('slots.is_occupied','=',1);
            })
            ->leftJoin('vehicles', function ($join) {
                $join->on('vehicles.id','=','user_slots.id');
            })
            ;
        return DataTables::of($locations)->make(true);

    }

    public function blockSlot($id,Request $request){
        $location = Slot::where('id',$id)->first();
        if($location->is_block==1){
            $location->is_block=0;
            $request->session()->flash('message', 'Slot No : '.$location->slot_id.' unblocked!');

        }else if($location->is_block==0){
            $location->is_block=1;
            $request->session()->flash('error', 'Slot No : '.$location->slot_id.' blocked!');

        }
        $location->save();

        return Redirect::back();

    }
    public function map($id)
    {
        $location = Location::find( $id);

        return view('admin.locations.map',compact('location'));


    }
    public function mapPost($id,Request $request)
    {
        $location = Location::find( $id);
        $location->lng = $request->input("lng");
        $location->lat = $request->input("lat");
        $location->save();
        return redirect()->back();
    }

}

resources/views/admin/locations/locations.blade.php
@extends('layouts.app_dashboard_admin')

@section("css")
    <style>
        table tr td:nth-child(5) {
            text-align: right;
        }
        .paginate_button {
            cursor: pointer;
        }
    </style>
@endsection
@section('content')
              {{--   <div class=""> --}}
                   {{--  <div class="clearfix"></div> --}}
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    <!-- <h2>Payment Getway </h2> -->

                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                <div class="x_title">
                                <h2>Locations </h2>


                                <ul class="nav navbar-right panel_toolbox">

                                    <a class="btn btn-primary" href="{{route("admin.addLocations")}}">Create More Locations</a>
                                   </ul>

                    <ul class="nav navbar-right panel_toolbox">

                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="table-responsive">
                                    <table id="table" class="table table-striped table-bordered">
                                            <thead>
                                                 <tr>
                                                    <td>Name</td>
                                                    <td>Price</td>
                                                    <td>Number of Slots</td>
                                                    <td>Payment Type</td>
                                                    <td>Vehicle Stand Type</td>
                                                    <td>User Type</td>



                                                    <td>Status</td>
                                                    <td>Action</td>


                                                    </tr>
                                                </thead>


                                    </table>
                                </div>
                            </div>
                        </div>
                        </div>

                    </div>
               {{--  </div> --}}


@endsection

@section("script")

<script type="text/javascript">
    $(document).ready(function () {

       var data_table = $('#table').DataTable({

       processing: true,
       serverSide: true,
       "iDisplayLength": 100,
       stateSave: true,
       "order": [[ 0, "desc" ]],
       ajax: {url:'{!! route('admin.ajaxLocation') !!}',
              data: function (d) {
              d.status = $('#filter-status').val();
              d.terminal = $('#filter-terminal').val();
              d.client = $('#filter-client').val();
              d.order_id = $('#order_id').val();

       }},
       columns: [

          {

                  "mData": null,

                  name: 'name',
                  "mRender": function (data) {
                        var edit = "{{ route('admin.viewLocation',':number') }}"
                        edit = edit.replace(':number', data.id);
                          return `<a title="view" href=${edit} style='color:blue'>${data.name}</a>`;

                       }
           },
          { data: 'price', name: 'price' },
          { data: 'number_of_slots', name: 'number_of_slots' },
          {
                  data: 'is_paid',
                  name: 'is_paid',
                  "mRender": function (data) {
                      if(data== 1)
                          return `<span class="label label-success">PAID</span>`;
                      else
                         return `<span class="label label-primary">FREE</span>`;
                          return data;
                       }
           },
          { data: 'vehicle_type_name', name: 'vehicle_type.name' },
          { data: 'user_type_name', name: 'user_type.name' },

          {
                  data: 'is_active',
                  name: 'is_active',
                  "mRender": function (data) {
                      if(data== 1)
                          return `<span class="label label-success">Active</span>`;
                      else
                         return `<span class="label label-danger">Blocked</span>`;
                          return data;
                       }
           },
           {
                    "mData": null,
                    "bSortable": false,
                    "bSearchable": false,
                    stateSave: true,
                    "mRender": function(data) {
                        var edit = "{{ route('admin.editLocation',':number') }}"
                        edit = edit.replace(':number', data.id);

                        var block = "{{ route('admin.blockLocation',':number') }}"
                        block = block.replace(':number', data.id);

                        var map = "{{ route('admin.map',':number') }}"
                        map = map.replace(':number', data.id);
                        if(data.is_active==1)
                            return `
                            <div class="btn-group">
                            <a  class="btn dropdown-toggle" data-toggle="dropdown" data-disabled="true" aria-expanded="true">Options <span class="caret"></span></a>
                                <ul class="dropdown-menu dropdown-menu-left" role="menu" style="left:unset !important;right:0px;">
                                        <li><a title="Edit" href=${edit}><i class="fa fa-pencil"></i> Edit</a></li>
                                        <li><a title="Edit" href=${map}><i class="fa fa-map"></i> Map</a></li>
                                        <li><a title="Edit" href=${block}><i class="fa fa-trash"></i> Block</a></li>
                                </ul>
                            </div>`
                        else if(data.is_active==0)
                            return `
                            <div class="btn-group">
                            <a  class="btn dropdown-toggle" data-toggle="dropdown" data-disabled="true" aria-expanded="true">Options <span class="caret"></span></a>
                                <ul class="dropdown-menu dropdown-menu-left" role="menu" style="left:unset !important;right:0px;">
                                        <li><a title="Edit" href=${edit}><i class="fa fa-pencil"></i> Edit</a></li>
                                        <li><a title="Edit" href=${block}><i class="fa fa-trash"></i> Unblock</a></li>
                                </ul>
                            </div>`

                    }
                }

           ]
       });

       $('.filter').on('change', function (e) {

           data_table.draw();
       });
       $( ".filter" ).keyup(function() {
           data_table.draw();
       });
   });
   </script>
    <style>
        .current
        {
            background-color: #DDD !important;
        }
    </style>
@endsection

resources/views/admin/locations/slots.blade.php
@extends('layouts.app_dashboard_admin')

@section("css")
    <style>
        table tr td:nth-child(5) {
            text-align: right;
        }
        .paginate_button {
            cursor: pointer;
        }

    </style>
@endsection
@section('content')
<style>
 .boxes{
            position: inline-block;

        }

    </style>
              {{--   <div class=""> --}}
                   {{--  <div class="clearfix"></div> --}}
                    <div class="row">

                            <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="x_panel">
                                        <div class="x_title">
                                            <h2>Locations <small>{{$location->name}}</small></h2>
                                            <ul class="nav navbar-right panel_toolbox">
                                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                                </li>
                                                </li>
                                            </ul>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="x_content">

                                            <div class="active_slot" style="margin-left:2px;width: 50px;height: 50px;background-color: greenyellow;display: inline-block;border-radius: 16px;"><cener><h2>1<h2/></center></div>




                                        </div>
                                    </div>
                                </div>

                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    <!-- <h2>Payment Getway </h2> -->

                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                <div class="x_title">
                                <h2>Locations  :: {{$location->name}} <small> Total Slots:  {{$location->number_of_slots}} </small> </h2>


                                <ul class="nav navbar-right panel_toolbox">

                                    <a class="btn btn-primary" href="{{route("admin.addSlots",$location->id)}}">Add Slots</a>
                                   </ul>

                    <ul class="nav navbar-right panel_toolbox">

                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="table-responsive">
                                    <table id="table" class="table table-striped table-bordered">
                                            <thead>
                                                 <tr>
                                                    <td>Slot ID</td>
                                                    <td>Availibility</td>
                                                    <td>Status</td>
                                                    <td>Vehicle #</td>

                                                    <td>Action</td>



                                                    </tr>
                                                </thead>


                                    </table>
                                </div>
                            </div>
                        </div>
                        </div>

                    </div>
               {{--  </div> --}}


@endsection

@section("script")

<script type="text/javascript">
    $(document).ready(function () {

       var data_table = $('#table').DataTable({

       processing: true,
       serverSide: true,
       "iDisplayLength": 100,
       stateSave: true,
       "order": [[ 0, "desc" ]],
       ajax: {url:'{!! route('admin.ajaxSlots') !!}',
              data: function (d) {
              d.status = $('#filter-status').val();
              d.terminal = $('#filter-terminal').val();
              d.client = $('#filter-client').val();
              d.order_id = $('#order_id').val();
              d.location_id = {{$location->id}};

       }},
       columns: [


          { data: 'slot_id', name: 'slot_id' },
          {
                  data: 'is_booked',
                  name: 'is_booked',
                  "mRender": function (data) {
                      if(data== 1)
                          return `<span class="label label-success">BOOKED</span>`;
                      else
                         return `<span class="label label-primary">AVAILABLE</span>`;

                       }
           },
           {
                  data: 'is_block',
                  name: 'is_block',
                  "mRender": function (data) {
                      if(data== 1)
                          return `<span class="label label-danger">BLOCKED</span>`;
                      else
                         return `<span class="label label-primary">Active</span>`;

                       }
           },
           { data: 'number_plate', name: 'number_plate' },

           {
                    "mData": null,
                    "bSortable": false,
                    "bSearchable": false,
                    stateSave: true,
                    "mRender": function(data) {
                       var block = "{{ route('admin.blockSlot',':number') }}"
                        block = block.replace(':number', data.id);
                        if(data.is_block==0)
                            return `
                            <div class="btn-group">
                            <a  class="btn dropdown-toggle" data-toggle="dropdown" data-disabled="true" aria-expanded="true">Options <span class="caret"></span></a>
                                <ul class="dropdown-menu dropdown-menu-left" role="menu" style="left:unset !important;right:0px;">
                                        <li><a title="Edit" href=${block}><i class="fa fa-trash"></i> Block</a></li>
                                </ul>
                            </div>`
                        else if(data.is_block==1)
                            return `
                            <div class="btn-group">
                            <a  class="btn dropdown-toggle" data-toggle="dropdown" data-disabled="true" aria-expanded="true">Options <span class="caret"></span></a>
                                <ul class="dropdown-menu dropdown-menu-left" role="menu" style="left:unset !important;right:0px;">
                                        <li><a title="Edit" href=${block}><i class="fa fa-pencil"></i> Unblock</a></li>
                                 </ul>
                            </div>`

                    }
                }

           ]
       });

       $('.filter').on('change', function (e) {

           data_table.draw();
       });
       $( ".filter" ).keyup(function() {
           data_table.draw();
       });
   });
   </script>
    <style>
        .current
        {
            background-color: #DDD !important;
        }
    </style>
@endsection