routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/home', function () { return redirect()->route('home'); })->name("main");
Route::get('/loader', function () { return view('management.dashboard.loader'); })->name("loader");

Auth::routes();
Route::group(['middleware' => ['auth','parking_stop_if_blocked']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/card', 'UserController@card')->name('card');
    Route::get('/plate-sticker', 'UserController@plateSticker')->name('plateSticker');

});

Route::group(['prefix' =>'admin','namespace'=>'Admin'], function () {
    // Admin Login Routes
    Route::get('/login','Auth\LoginController@showLoginForm')->name('admin.login');
    Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('/register','Auth\RegisterController@register');
    Route::post('/login','Auth\LoginController@login');
    Route::post('/logout','Auth\LoginController@logout')->name('admin.logout');
    //Forgot Password Routes
    Route::get('/password/reset','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    //Reset Password Routes
    Route::get('/password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/password/reset','Auth\ResetPasswordController@reset')->name('password.update');
});

Route::group(['prefix' =>'admin','namespace'=>'Admin','as' => 'admin.','middleware' => ['auth:admin']], function () {
    Route::get('/',function(){ return redirect()->route('admin.dashboard'); })->name('home');
    Route::get('/dashboard','HomeController@index')->name('dashboard');
    Route::get('/managements','ManagementController@managements')->name('managements');
    Route::get('/management/add','ManagementController@addManagement')->name('addManagement');
    Route::post('/add-management','ManagementController@addManagementPost')->name('addManagementPost');
    Route::get('/ajax-managements','ManagementController@ajaxManagements')->name('ajaxManagements');
    Route::get('/management/edit/{id}','ManagementController@editManagement')->name('editManagement');
    Route::post('/edit-management','ManagementController@editManagementPost')->name('editManagementPost');
    Route::get('/management/block/{id}','ManagementController@blockManagement')->name('blockManagement');

    Route::get('/vehicle/types','ManagementController@vehicleTypes')->name('vehicleTypes');
    Route::get('/vehicle/types/edit/{id}','ManagementController@editVehicleType')->name('editVehicleType');
    Route::post('/vehicle/types/edit/{id}/post','ManagementController@editVehicleTypePost')->name('editVehicleTypePost');

    Route::get('/vehicle/types/add','ManagementController@addVehicleType')->name('addVehicleType');
    Route::post('/vehicle/types/add','ManagementController@addVehicleTypePost')->name('addVehicleTypePost');
    Route::get('/ajax-vehicle/types/','ManagementController@ajaxVehicleType')->name('ajaxVehicleType');

    Route::get('/location','LocationController@location')->name('location');
    Route::get('/location/add','LocationController@addLocations')->name('addLocations');
    Route::post('/add-locations','LocationController@addLocationPost')->name('addLocationPost');
    Route::get('/ajax-locations','LocationController@ajaxLocation')->name('ajaxLocation');
    Route::get('/location/edit/{id}','LocationController@editLocation')->name('editLocation');
    Route::post('/edit-location/post','LocationController@editLocationPost')->name('editLocationPost');
    Route::get('/location/block/{id}','LocationController@blockLocation')->name('blockLocation');
    Route::get('/location/map/{id}','LocationController@map')->name('map');
    Route::post('/location/map/{id}/post','LocationController@mapPost')->name('mapPost');

    Route::get('/location/{id}','LocationController@viewLocation')->name('viewLocation');

    Route::get('/slots/{id}','LocationController@addSlots')->name('addSlots');
    Route::post('/location/add/post','LocationController@addSlotPost')->name('addSlotPost');
    Route::get('/ajax-slots','LocationController@ajaxSlots')->name('ajaxSlots');
    Route::get('/slots/block/{id}','LocationController@blockSlot')->name('blockSlot');

    Route::get('/user-type','ManagementController@usersTypes')->name('usersTypes');
    Route::get('/user-type/add','ManagementController@addUserType')->name('addUserType');
    Route::post('/user-type/add/post','ManagementController@addUserTypePost')->name('addUserTypePost');
    Route::get('/ajax/users/','ManagementController@ajaxUserType')->name('ajaxUserType');

    Route::get('/users','ManagementController@users')->name('users');
    Route::get('/users/add','ManagementController@addUsers')->name('addUsers');
    Route::post('/users/add/post','ManagementController@addUserPost')->name('addUserPost');
    Route::post('/ajax-check-user-type','ManagementController@ajaxCheckUserType')->name('ajaxCheckUserType');
    Route::get('/ajax-users','ManagementController@ajaxUsers')->name('ajaxUsers');
    Route::post('/users-vehicles','ManagementController@usersVehicles')->name('usersVehicles');
    Route::get('/recharge/{id}','ManagementController@recharge')->name('recharge');
    Route::post('/recharge/{id}/post','ManagementController@rechargePost')->name('rechargePost');
    Route::get('/user/block/{id}','ManagementController@blockUser')->name('blockUser');


    Route::get('/parking-detail','ParkingController@parkingDetail')->name('parkingDetail');
    Route::get('/ajax-parking-detail','ParkingController@ajaxParkingDetail')->name('ajaxParkingDetail');







  });

  Route::group(['prefix' =>'management','namespace'=>'Management'], function () {
    // Admin Login Routes
    Route::get('/login','Auth\LoginController@showLoginForm')->name('management.login');
    Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('management.register');
    Route::post('/register','Auth\RegisterController@register');
    Route::post('/login','Auth\LoginController@login');
    Route::post('/logout','Auth\LoginController@logout')->name('management.logout');
    //Forgot Password Routes
});

Route::group(['prefix' =>'management','namespace'=>'Management','middleware' => ['auth:management','stop_if_blocked']], function () {
    Route::get('/',function(){ return redirect()->route('management.dashboard'); })->name('management.home');
    //Route::get('/dashboard','HomeController@index')->name('management.dashboard');
    Route::get('/dashboard',function(){ return redirect()->route('management.checkPoint'); })->name('management.dashboard');
    Route::get('/check-point/in','ManagementController@checkPoint')->name('management.checkPoint');
    Route::post('/ajax-check-user','ManagementController@ajaxVerifyUser')->name('management.ajaxVerifyUser');
    Route::get('/check-point/out','ManagementController@checkPointOut')->name('management.checkPointOut');
    Route::post('/ajax-check-point/out','ManagementController@ajaxVerifyUserOut')->name('management.ajaxVerifyUserOut');


  });

app/Http/Controllers/Admin/ManagementController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use Auth;
use DataTables;
use Illuminate\Support\Facades\Validator;
use App\Model\Management;
use App\Model\UserBalance;
use Illuminate\Support\Facades\Hash;
use Redirect;
use App\Model\VehicleType;
use App\Model\UserType;
use App\Model\Vehicle;
use App\User;

class ManagementController extends Controller
{

    public function managements()
    {

        return view('admin.managements.managements');
    }
    public function addManagement()
    {

        return view('admin.managements.add-management');
    }

    public function addManagementPost(Request $request){

        $validator =  Validator::make($request->all(),[
            'email' => 'required|unique:managements|min:7,email',
            'username' => 'required|unique:managements|min:4',
            'password' => 'required|min:6',
            'name' => 'required|min:3',
        ]);

        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        }



        Management::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'username' => $request->input('username'),
            'institute_id' => Auth::guard('admin')->user()->institute_id,
            'admin_id' => Auth::guard('admin')->user()->id,
            'password' => Hash::make($request->input('password')),
        ]);
        $request->session()->flash('message', 'User created successfully!');
        return Redirect::back();
    }
    public function ajaxManagements(Request $request){
        $management=Management::where('institute_id',Auth::guard('admin')->user()->institute_id);
        return DataTables::of($management)->make(true);
    }
    public function editManagement($id){
        $management=Management::find($id);
        return view('admin.managements.edit-management',compact('management'));
    }

    public function editManagementPost(Request $request){

        $validator =  Validator::make($request->all(),[
            'email' => 'required|min:7,email',
            'username' => 'required|min:4',

            'name' => 'required|min:3',
        ]);

        if($request->input('password')){
            $validator =  Validator::make($request->all(),[
               'password' => 'required|min:6',
            ]);
        }
        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        }



        $management = Management::where('id',$request->input('id'))->first();
        $management->email = $request->input('email');
        $management->name = $request->input('name');
        $management->username = $request->input('username');
        if($request->input('password')){
            $management->password = Hash::make($request->input('password'));

        }
        $management->save();

        $request->session()->flash('message', 'User : '.$management->name.' updated successfully!');
        return Redirect::back();
    }
    public function blockManagement($id,Request $request){
        $management = Management::where('id',$id)->first();
        if($management->is_active==1){
            $management->is_active=0;
        }else if($management->is_active==0){
            $management->is_active=1;
        }
        $management->save();
        $request->session()->flash('message', 'User : '.$management->name.' blocked!');

        return Redirect::back();

    }
    public function blockUser($id,Request $request){
        $management = User::where('id',$id)->first();
        if($management->is_active==1){
            $management->is_active=0;
            $request->session()->flash('message', 'User : '.$management->name.' unblocked!');

        }else if($management->is_active==0){
            $management->is_active=1;
            $request->session()->flash('message', 'User : '.$management->name.' blocked!');

        }

        $management->save();
        return Redirect::back();

    }


    public function vehicleTypes()
    {
        return view('admin.managements.vehicle-types');
    }
    public function editVehicleType($id)
    {
        $vehicleType = VehicleType::find($id);
        return view('admin.managements.edit-vehicle-types',compact('vehicleType'));
    }
    public function editVehicleTypePost($id,Request $request)
    {
        $vehicleType = VehicleType::find($id);
        $vehicleType->name = $request->input("name");
        $vehicleType->save();
        return Redirect::back();
     }

    public function addVehicleType()
    {
        return view('admin.managements.add-vehicle-types');
    }

    public function addVehicleTypePost(Request $request){
        $vehicleType = VehicleType::create([
            'name' => $request->input('name'),

            'institute_id' => Auth::guard('admin')->user()->institute_id,
            'admin_id' => Auth::guard('admin')->user()->id,
        ]);
        $request->session()->flash('message', 'User : '.$vehicleType->name.' created successfully!');
        return redirect()->route("admin.vehicleTypes");
    }
    public function ajaxVehicleType()
    {
        $management=VehicleType::where('institute_id',Auth::guard('admin')->user()->institute_id)->where('admin_id',Auth::guard('admin')->user()->id);
        return DataTables::of($management)->make(true);
    }
    public function usersTypes(){
        return view('admin.managements.user-types');
    }
    public function addUserType(){
        return view('admin.managements.add-user-types');
    }
    public function addUserTypePost(Request $request)
    {
        $vehicleType = UserType::create([
            'name' => $request->input('name'),
            'is_paid' => $request->input('is_paid'),
            'institute_id' => Auth::guard('admin')->user()->institute_id,
            'admin_id' => Auth::guard('admin')->user()->id,
        ]);
        $request->session()->flash('message', ' '.$vehicleType->name.' created successfully!');
        return redirect()->route("admin.usersTypes");
    }
    public function ajaxUserType(Request $request){
        $management=UserType::where('institute_id',Auth::guard('admin')->user()->institute_id);
        return DataTables::of($management)->make(true);
    }
    public function users()
    {
        return view('admin.managements.users');
    }
    public function addUsers()
    {
        $vehicleTypes=VehicleType::select('name','id')->where('institute_id',Auth::guard('admin')->user()->institute_id)->get();
        $userTypes=UserType::select('name','id')->where('institute_id',Auth::guard('admin')->user()->institute_id)->get();
        return view('admin.managements.add-users',compact('vehicleTypes','userTypes'));
    }
    public function ajaxCheckUserType(Request $request){
        $user_type=UserType::where('id',$request->input('user_type_id'))->first();
        return $user_type->is_paid;
    }
    function generateCode($limit){
        $code = 0;
        for($i = 0; $i < $limit; $i++) { $code .= mt_rand(0, 9); }
        return $code;
    }
    public function addUserPost(Request $request){
        //dd($request->all());
        /* $validator =  Validator::make($request->all(),[
            'email' => 'required|min:7,email,unique:users',
            'username' => 'required|min:4',

            'name' => 'required|min:3',
        ]);
        dd($validator->fails());
        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        } */
        $user = new User;
        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->user_type_id = $request->input('user_type_id');

        $user->password = Hash::make($request->input('password'));
        $user->password_string = $request->input('password');
        $user->generated_id = $this->generateCode(14);

        $user->username = $request->input('username');
        $user->institute_id =  Auth::guard('admin')->user()->institute_id;
        $user->save();

        if($request->input('balance')){
            $user->balance = $request->input('balance');
            $user->save();
            UserBalance::create([
                'amount'=>$user->balance,
                'user_id'=>$user->id,
                'is_deposit'=>1
            ]);
        }
        if($request->input('vehicle')){
            $array = $request->input('vehicle');
            $user->save();

            $newArray = array();
            foreach (array_keys($array) as $fieldKey) {
                foreach ($array[$fieldKey] as $key=>$value) {
                    $newArray[$key][$fieldKey] = $value;
                }
            }
            $vehicles = $newArray;
            foreach($vehicles as $vehicle){
                if(isset($vehicle['number']))
                Vehicle::create([
                    'vehicle_number'=>@$vehicle['number'],
                    'vehicle_type_id'=>@$vehicle['type_id'],
                    'institute_id'=> Auth::guard('admin')->user()->institute_id,
                    'user_id'=> $user->id,
                ]);

            }
        }
        $request->session()->flash('message', 'User : '.$user->name.' created successfully!');
        return Redirect::back();

    }
    public function ajaxUsers()
    {
        $management=User::select('users.*','user_type.is_paid','user_type.name as user_type_name')->where('users.institute_id',Auth::guard('admin')->user()->institute_id)
        ->join('user_type', 'user_type.id', '=', 'users.user_type_id');

        return DataTables::of($management)->make(true);
    }
    public function usersVehicles(Request $request)
    {

resources/views/admin/managements/users.blade.php
@extends('layouts.app_dashboard_admin')

@section("css")
    <style>
        table tr td:nth-child(5) {
            text-align: right;
        }
        .paginate_button {
            cursor: pointer;
        }
    </style>
@endsection
@section('content')
              {{--   <div class=""> --}}
                   {{--  <div class="clearfix"></div> --}}
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    <!-- <h2>Payment Getway </h2> -->

                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                <div class="x_title">
                                <h2>Users </h2>


                                <ul class="nav navbar-right panel_toolbox">

                                    <a class="btn btn-primary" href="{{route("admin.addUsers")}}">Add Users</a>
                                   </ul>

                    <ul class="nav navbar-right panel_toolbox">

                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="table-responsive">
                                    <table id="table" class="table table-striped table-bordered">
                                            <thead>
                                                 <tr>
                                                    <td>Type Name</td>
                                                    <td>Name</td>
                                                    <td>Email</td>
                                                    <td>Username</td>
                                                    <td>Balance</td>
                                                    <td>Password</td>
                                                    <td>Barcode ID</td>

                                                    <td>Created Date</td>
                                                    <td>Vehicles</td>

                                                    <td>Status</td>
                                                    <td>Type</td>
                                                    <td>Action</td>


                                                    </tr>
                                                </thead>


                                    </table>
                                </div>
                            </div>
                        </div>
                        </div>

                    </div>
               {{--  </div> --}}
               <!-- Modal -->
            <div id="myModal" class="modal fade" role="dialog">
                <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">User : <span id="user_name"><span></h4>
                    </div>
                    <div class="modal-body">
                    <p>Details</p>
                    <p id="vehicle_content"></p>
                    </div>

                </div>

                </div>
            </div>


@endsection

@section("script")

<script type="text/javascript">
    $(document).ready(function () {

       var data_table = $('#table').DataTable({

       processing: true,
       serverSide: true,
       "iDisplayLength": 100,
       stateSave: true,
       "order": [[ 0, "desc" ]],
       ajax: {url:'{!! route('admin.ajaxUsers') !!}',
              data: function (d) {
              d.status = $('#filter-status').val();
              d.terminal = $('#filter-terminal').val();
              d.client = $('#filter-client').val();
              d.order_id = $('#order_id').val();

       }},
       columns: [
        {
                  data: 'user_type_name',
                  name: 'user_type_name',
                  "mRender": function (data) {
                      return data;
                }
           },
          { data: 'name', name: 'name' },
          { data: 'email', name: 'email' },
          { data: 'username', name: 'username' },
          { data: 'balance', name: 'balance' },
          { data: 'password_string', name: 'password_string' },
          { data: 'generated_id', name: 'generated_id' },
          { data: 'created_at', name: 'created_at' },

          {
                    "mData": null,
                    "bSortable": false,
                    "bSearchable": false,
                    stateSave: true,
                  "mRender": function (data) {
                      return `<span name=${data.name} value=${data.id} class="label label-primary vehicles">view <i class="fas fa-bicycle"></i> </span>`;

                       }
           },
          {
                  data: 'is_active',
                  name: 'is_active',
                  "mRender": function (data) {
                      if(data== 1)
                          return `<span class="label label-success">Active</span>`;
                      else
                         return `<span class="label label-warning">Blocked</span>`;
                          return data;
                       }
           },
           {
                  data: 'is_paid',
                  name: 'is_paid',
                  "mRender": function (data) {
                      if(data== 1)
                          return `<span class="label label-success">Paid</span>`;
                      else
                         return `<span class="label label-warning">Free</span>`;
                          return data;
                       }
           },


           {
                    "mData": null,
                    "bSortable": false,
                    "bSearchable": false,
                    stateSave: true,
                    "mRender": function(data) {
                        var edit = "{{ route('admin.editManagement',':number') }}"
                        edit = edit.replace(':number', data.id);

                        var block = "{{ route('admin.blockUser',':number') }}"
                        block = block.replace(':number', data.id);
                        var recharge = "{{ route('admin.recharge',':number') }}"
                        recharge = recharge.replace(':number', data.id);
                        if(data.is_active==1)
                            return `
                            <div class="btn-group">
                            <a  class="btn dropdown-toggle" data-toggle="dropdown" data-disabled="true" aria-expanded="true">Options <span class="caret"></span></a>
                                <ul class="dropdown-menu dropdown-menu-left" role="menu" style="left:unset !important;right:0px;">
                                        <li><a title="Edit" href=${recharge}><i class="fa fa-pencil"></i> Recharge</a></li>
                                       {{-- <li><a title="Edit" href=${edit}><i class="fa fa-pencil"></i> Edit</a></li> --}}
                                        <li><a title="Edit" href=${block}><i class="fa fa-trash"></i> Block</a></li>
                                </ul>
                            </div>`
                        else if(data.is_active==0)
                            return `
                            <div class="btn-group">
                            <a  class="btn dropdown-toggle" data-toggle="dropdown" data-disabled="true" aria-expanded="true">Options <span class="caret"></span></a>
                                <ul class="dropdown-menu dropdown-menu-left" role="menu" style="left:unset !important;right:0px;">
                                    <li><a title="Edit" href=${recharge}><i class="fa fa-pencil"></i> Recharge</a></li>
                                        <li><a title="Edit" href=${edit}><i class="fa fa-pencil"></i> Edit</a></li>
                                        <li><a title="Edit" href=${block}><i class="fa fa-trash"></i> Unblock</a></li>
                                </ul>
                            </div>`

                    }
                }

           ]
       });

       $('.filter').on('change', function (e) {

           data_table.draw();
       });
       $( ".filter" ).keyup(function() {
           data_table.draw();
       });

   });
   $(document).on("mouseenter", ".vehicles", function() {


        var user = $(this).attr('value')
        var name = $(this).attr('name')
        //$('#user_name').empty()
        //$('#user_name').append(name)

        $.ajax({
            headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            type:'POST',
            url:'{!! route('admin.usersVehicles') !!}',
            data: {
                user: user
            },

            success:function(data){
                var render_data ='';
                data.forEach(function(item) {
                    render_data += `<h5>${item.parent.name} : ${item.vehicle_number}</h5>`

                });
                //$('#vehicle_content').empty()
                //$('#vehicle_content').append(render_data)
                //console.log(render_data);
                //$('#myModal').modal('show');
                Swal.fire({
                title: `<strong>User <u>${name}</u></strong>`,
                type: 'info',
                html:render_data,
                showCloseButton: true,
                focusConfirm: false,
                confirmButtonText:
                    '<i class="fa fa-car"></i> Thanks!',
                })
            }
        });
    });
   </script>
    <style>
        .current
        {
            background-color: #DDD !important;
        }
    </style>
@endsection

resources/views/admin/managements/vehicle-types.blade.php
@extends('layouts.app_dashboard_admin')

@section("css")
    <style>
        table tr td:nth-child(5) {
            text-align: right;
        }
        .paginate_button {
            cursor: pointer;
        }
    </style>
@endsection
@section('content')
              {{--   <div class=""> --}}
                   {{--  <div class="clearfix"></div> --}}
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    <!-- <h2>Payment Getway </h2> -->

                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                <div class="x_title">
                                <h2>Vehicles type </h2>


                                <ul class="nav navbar-right panel_toolbox">

                                    <a class="btn btn-primary" href="{{route("admin.addVehicleType")}}">Add Vehicle Type</a>
                                   </ul>

                    <ul class="nav navbar-right panel_toolbox">

                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="table-responsive">
                                    <table id="table" class="table table-striped table-bordered">
                                            <thead>
                                                 <tr>
                                                    <td>Name</td>
                                                    <td>Action</td>
                                                    </tr>
                                                </thead>


                                    </table>
                                </div>
                            </div>
                        </div>
                        </div>

                    </div>
               {{--  </div> --}}


@endsection

@section("script")

<script type="text/javascript">
    $(document).ready(function () {

       var data_table = $('#table').DataTable({

       processing: true,
       serverSide: true,
       "iDisplayLength": 100,
       stateSave: true,
       "order": [[ 0, "desc" ]],
       ajax: {url:'{!! route('admin.ajaxVehicleType') !!}',
              data: function (d) {
              d.status = $('#filter-status').val();
              d.terminal = $('#filter-terminal').val();
              d.client = $('#filter-client').val();
              d.order_id = $('#order_id').val();

       }},
       columns: [
          { data: 'name', name: 'name' }
          ,
           {
                    "mData": null,
                    "bSortable": false,
                    "bSearchable": false,
                    stateSave: true,
                    "mRender": function(data) {

                        var block = "{{ route('admin.editVehicleType',':number') }}"
                        block = block.replace(':number', data.id);
                             return `
                            <a title="Edit" href=${block}><i class="fa fa-pencil"></i> Edit</a></li>`


                    }
                }
           ]
       });

       $('.filter').on('change', function (e) {

           data_table.draw();
       });
       $( ".filter" ).keyup(function() {
           data_table.draw();
       });
   });
   </script>
    <style>
        .current
        {
            background-color: #DDD !important;
        }
    </style>
@endsection